export const dummyData = [
  {
    id: '01',
    first_name: 'Haroun',
    surname: 'Galiford',
    age: 29,
    gender: 'Male',
    level: 400,
    state: 'Bayelsa State',
  },
  {
    id: '02',
    first_name: 'Reginauld',
    surname: 'McDonell',
    age: 15,
    gender: 'Male',
    level: 300,
    state: 'Lagos State',
  },
  {
    id: '03',
    first_name: 'Callie',
    surname: 'Gornar',
    age: 36,
    gender: 'Female',
    level: 700,
    state: 'Katsina State',
  },
  {
    id: '04',
    first_name: 'Carline',
    surname: 'McEneny',
    age: 26,
    gender: 'Female',
    level: 200,
    state: 'Imo State',
  },
  {
    id: '05',
    first_name: 'Jeno',
    surname: 'Dodd',
    age: 22,
    gender: 'Male',
    level: 200,
    state: 'Kaduna State',
  },
  {
    id: '06',
    first_name: 'Ferrell',
    surname: 'Revely',
    age: 22,
    gender: 'Male',
    level: 200,
    state: 'Enugu State',
  },
  {
    id: '07',
    first_name: 'Brittani',
    surname: 'Twidale',
    age: 38,
    gender: 'Female',
    level: 500,
    state: 'Kano State',
  },
  {
    id: '08',
    first_name: 'Alyosha',
    surname: 'Selcraig',
    age: 22,
    gender: 'Male',
    level: 400,
    state: 'Kebbi State',
  },
  {
    id: '09',
    first_name: 'Inger',
    surname: 'Dean',
    age: 30,
    gender: 'Male',
    level: 200,
    state: 'Edo State',
  },
  {
    id: 10,
    first_name: 'Hilarius',
    surname: 'Graeber',
    age: 45,
    gender: 'Male',
    level: 500,
    state: 'Kaduna State',
  },
  {
    id: 11,
    first_name: 'Carmel',
    surname: 'Sehorsch',
    age: 27,
    gender: 'Female',
    level: 400,
    state: 'Nasarawa State',
  },
  {
    id: 12,
    first_name: 'Rica',
    surname: 'Rizzini',
    age: 44,
    gender: 'Female',
    level: 200,
    state: 'Ebonyi State',
  },
  {
    id: 13,
    first_name: 'Ailsun',
    surname: 'Hansen',
    age: 34,
    gender: 'Female',
    level: 500,
    state: 'Gombe State',
  },
  {
    id: 14,
    first_name: 'Bram',
    surname: 'MacNeill',
    age: 30,
    gender: 'Male',
    level: 200,
    state: 'Oyo State',
  },
  {
    id: 15,
    first_name: 'Leah',
    surname: 'Griston',
    age: 55,
    gender: 'Female',
    level: 100,
    state: 'Niger State',
  },
  {
    id: 16,
    first_name: 'Robbin',
    surname: 'Clough',
    age: 54,
    gender: 'Female',
    level: 400,
    state: 'Delta State',
  },
  {
    id: 17,
    first_name: 'Osbourn',
    surname: 'Yendall',
    age: 36,
    gender: 'Male',
    level: 200,
    state: 'Rivers State',
  },
  {
    id: 18,
    first_name: 'Fionnula',
    surname: 'Wharin',
    age: 39,
    gender: 'Female',
    level: 200,
    state: 'Cross River State',
  },
  {
    id: 19,
    first_name: 'Eolanda',
    surname: 'Entwisle',
    age: 38,
    gender: 'Female',
    level: 200,
    state: 'Kogi State',
  },
  {
    id: 20,
    first_name: 'Sigfrid',
    surname: 'Belfit',
    age: 18,
    gender: 'Male',
    level: 100,
    state: 'Benue State',
  },
  {
    id: 21,
    first_name: 'Aime',
    surname: 'Baunton',
    age: 31,
    gender: 'Female',
    level: 500,
    state: 1,
  },
  {
    id: 22,
    first_name: 'Aurea',
    surname: 'Dolby',
    age: 21,
    gender: 'Female',
    level: 700,
    state: 1,
  },
  {
    id: 23,
    first_name: 'Rudolfo',
    surname: 'Georgins',
    age: 50,
    gender: 'Male',
    level: 700,
    state: 1,
  },
  {
    id: 24,
    first_name: 'Gene',
    surname: 'Mewis',
    age: 23,
    gender: 'Male',
    level: 600,
    state: 1,
  },
  {
    id: 25,
    first_name: 'Alana',
    surname: 'Itzkovwitch',
    age: 53,
    gender: 'Female',
    level: 600,
    state: 1,
  },
  {
    id: 26,
    first_name: 'Barnie',
    surname: "O'Grada",
    age: 12,
    gender: 'Male',
    level: 700,
    state: 1,
  },
  {
    id: 27,
    first_name: 'Babara',
    surname: 'Fasse',
    age: 54,
    gender: 'Female',
    level: 600,
    state: 1,
  },
  {
    id: 28,
    first_name: 'Rosalyn',
    surname: 'Leile',
    age: 34,
    gender: 'Female',
    level: 500,
    state: 1,
  },
  {
    id: 29,
    first_name: 'Rafaela',
    surname: 'Dryburgh',
    age: 31,
    gender: 'Female',
    level: 600,
    state: 1,
  },
  {
    id: 30,
    first_name: 'Orren',
    surname: 'Revely',
    age: 34,
    gender: 'Male',
    level: 700,
    state: 1,
  },
  {
    id: 31,
    first_name: 'Horton',
    surname: 'Cranney',
    age: 57,
    gender: 'Male',
    level: 100,
    state: 1,
  },
  {
    id: 32,
    first_name: 'Millard',
    surname: 'Abramowitch',
    age: 59,
    gender: 'Male',
    level: 600,
    state: 1,
  },
  {
    id: 33,
    first_name: 'Graehme',
    surname: 'Iffland',
    age: 53,
    gender: 'Male',
    level: 400,
    state: 1,
  },
  {
    id: 34,
    first_name: 'Malina',
    surname: 'Plaschke',
    age: 38,
    gender: 'Female',
    level: 700,
    state: 1,
  },
  {
    id: 35,
    first_name: 'Hatty',
    surname: 'Korejs',
    age: 30,
    gender: 'Female',
    level: 500,
    state: 1,
  },
  {
    id: 36,
    first_name: 'Birgit',
    surname: 'Saura',
    age: 36,
    gender: 'Female',
    level: 100,
    state: 1,
  },
  {
    id: 37,
    first_name: 'Tremaine',
    surname: 'Daintree',
    age: 25,
    gender: 'Male',
    level: 100,
    state: 1,
  },
  {
    id: 38,
    first_name: 'Felicia',
    surname: 'Webland',
    age: 48,
    gender: 'Female',
    level: 400,
    state: 1,
  },
  {
    id: 39,
    first_name: 'Spike',
    surname: 'Leake',
    age: 48,
    gender: 'Male',
    level: 600,
    state: 1,
  },
  {
    id: 40,
    first_name: 'Padraig',
    surname: 'Thew',
    age: 34,
    gender: 'Male',
    level: 500,
    state: 1,
  },
  {
    id: 41,
    first_name: 'Goober',
    surname: 'Coad',
    age: 45,
    gender: 'Male',
    level: 100,
    state: 1,
  },
  {
    id: 42,
    first_name: 'Afton',
    surname: 'Wyne',
    age: 28,
    gender: 'Female',
    level: 500,
    state: 1,
  },
  {
    id: 43,
    first_name: 'Blair',
    surname: 'Thon',
    age: 32,
    gender: 'Female',
    level: 600,
    state: 1,
  },
  {
    id: 44,
    first_name: 'Sig',
    surname: 'Conahy',
    age: 54,
    gender: 'Male',
    level: 400,
    state: 1,
  },
  {
    id: 45,
    first_name: 'Cort',
    surname: 'Vondrach',
    age: 48,
    gender: 'Male',
    level: 400,
    state: 1,
  },
  {
    id: 46,
    first_name: 'Raviv',
    surname: 'Rabb',
    age: 20,
    gender: 'Male',
    level: 500,
    state: 1,
  },
  {
    id: 47,
    first_name: 'Danna',
    surname: 'Olifaunt',
    age: 51,
    gender: 'Female',
    level: 400,
    state: 1,
  },
  {
    id: 48,
    first_name: 'Wayne',
    surname: 'Rosentholer',
    age: 17,
    gender: 'Male',
    level: 300,
    state: 1,
  },
  {
    id: 49,
    first_name: 'Bord',
    surname: 'Hargerie',
    age: 24,
    gender: 'Male',
    level: 400,
    state: 1,
  },
  {
    id: 50,
    first_name: 'Trish',
    surname: 'Jedrysik',
    age: 16,
    gender: 'Female',
    level: 300,
    state: 1,
  },
  {
    id: 51,
    first_name: 'Ganny',
    surname: 'Kilfeather',
    age: 21,
    gender: 'Male',
    level: 200,
    state: 1,
  },
  {
    id: 52,
    first_name: 'Melody',
    surname: 'Duinbleton',
    age: 32,
    gender: 'Female',
    level: 400,
    state: 1,
  },
  {
    id: 53,
    first_name: 'Gregoire',
    surname: 'Ortner',
    age: 37,
    gender: 'Male',
    level: 700,
    state: 1,
  },
  {
    id: 54,
    first_name: 'Emogene',
    surname: 'Paskins',
    age: 22,
    gender: 'Female',
    level: 100,
    state: 1,
  },
  {
    id: 55,
    first_name: 'Errick',
    surname: 'de Clercq',
    age: 42,
    gender: 'Male',
    level: 200,
    state: 1,
  },
  {
    id: 56,
    first_name: 'Bailey',
    surname: 'Coltan',
    age: 46,
    gender: 'Male',
    level: 500,
    state: 1,
  },
  {
    id: 57,
    first_name: 'Anthiathia',
    surname: 'Greig',
    age: 47,
    gender: 'Female',
    level: 400,
    state: 1,
  },
  {
    id: 58,
    first_name: 'Jamaal',
    surname: 'Biaggioli',
    age: 49,
    gender: 'Male',
    level: 200,
    state: 1,
  },
  {
    id: 59,
    first_name: 'Gwendolen',
    surname: 'Syphas',
    age: 55,
    gender: 'Female',
    level: 200,
    state: 1,
  },
  {
    id: 60,
    first_name: 'Dennis',
    surname: 'Kenway',
    age: 58,
    gender: 'Male',
    level: 600,
    state: 1,
  },
  {
    id: 61,
    first_name: 'Smith',
    surname: 'Woolis',
    age: 34,
    gender: 'Male',
    level: 200,
    state: 1,
  },
  {
    id: 62,
    first_name: 'Dru',
    surname: 'Crimp',
    age: 42,
    gender: 'Male',
    level: 100,
    state: 1,
  },
  {
    id: 63,
    first_name: 'Marys',
    surname: 'Thomtson',
    age: 59,
    gender: 'Female',
    level: 200,
    state: 1,
  },
  {
    id: 64,
    first_name: 'August',
    surname: 'Banke',
    age: 28,
    gender: 'Male',
    level: 500,
    state: 1,
  },
  {
    id: 65,
    first_name: 'Gavra',
    surname: 'Sindell',
    age: 36,
    gender: 'Female',
    level: 300,
    state: 1,
  },
  {
    id: 66,
    first_name: 'Sayre',
    surname: 'Doud',
    age: 29,
    gender: 'Female',
    level: 100,
    state: 1,
  },
  {
    id: 67,
    first_name: 'Diane',
    surname: 'Pizey',
    age: 56,
    gender: 'Female',
    level: 700,
    state: 1,
  },
  {
    id: 68,
    first_name: 'Terrill',
    surname: 'Bullman',
    age: 28,
    gender: 'Male',
    level: 200,
    state: 1,
  },
  {
    id: 69,
    first_name: 'Melony',
    surname: 'Gynni',
    age: 31,
    gender: 'Female',
    level: 300,
    state: 1,
  },
  {
    id: 70,
    first_name: 'Enrika',
    surname: 'Sambiedge',
    age: 40,
    gender: 'Female',
    level: 100,
    state: 1,
  },
  {
    id: 71,
    first_name: 'Dickie',
    surname: 'Boundey',
    age: 55,
    gender: 'Male',
    level: 700,
    state: 1,
  },
  {
    id: 72,
    first_name: 'Marlo',
    surname: 'Evreux',
    age: 45,
    gender: 'Male',
    level: 300,
    state: 1,
  },
  {
    id: 73,
    first_name: 'Kandy',
    surname: 'Meaden',
    age: 29,
    gender: 'Female',
    level: 700,
    state: 1,
  },
  {
    id: 74,
    first_name: 'Waring',
    surname: "O'Caine",
    age: 41,
    gender: 'Male',
    level: 500,
    state: 1,
  },
  {
    id: 75,
    first_name: 'Gerianne',
    surname: 'Roskelley',
    age: 34,
    gender: 'Female',
    level: 500,
    state: 1,
  },
  {
    id: 76,
    first_name: 'Zared',
    surname: 'Locard',
    age: 39,
    gender: 'Male',
    level: 200,
    state: 1,
  },
  {
    id: 77,
    first_name: 'Annaliese',
    surname: 'Trayling',
    age: 58,
    gender: 'Female',
    level: 600,
    state: 1,
  },
  {
    id: 78,
    first_name: 'Fenelia',
    surname: 'Wrought',
    age: 41,
    gender: 'Female',
    level: 200,
    state: 1,
  },
  {
    id: 79,
    first_name: 'Itch',
    surname: 'Isenor',
    age: 21,
    gender: 'Male',
    level: 300,
    state: 1,
  },
  {
    id: 80,
    first_name: 'Clemmy',
    surname: 'Furmonger',
    age: 28,
    gender: 'Female',
    level: 700,
    state: 1,
  },
  {
    id: 81,
    first_name: 'Ulrick',
    surname: 'Ivashnyov',
    age: 23,
    gender: 'Male',
    level: 200,
    state: 1,
  },
  {
    id: 82,
    first_name: 'Ileana',
    surname: 'Deeley',
    age: 25,
    gender: 'Female',
    level: 700,
    state: 1,
  },
  {
    id: 83,
    first_name: 'Shannon',
    surname: 'Gumb',
    age: 24,
    gender: 'Male',
    level: 600,
    state: 1,
  },
  {
    id: 84,
    first_name: 'Natale',
    surname: 'Franciskiewicz',
    age: 55,
    gender: 'Male',
    level: 400,
    state: 1,
  },
  {
    id: 85,
    first_name: 'Arlee',
    surname: 'Gayne',
    age: 38,
    gender: 'Female',
    level: 600,
    state: 1,
  },
  {
    id: 86,
    first_name: 'Cassaundra',
    surname: 'Vosper',
    age: 56,
    gender: 'Female',
    level: 600,
    state: 1,
  },
  {
    id: 87,
    first_name: 'Ronny',
    surname: 'Blenkinsop',
    age: 25,
    gender: 'Female',
    level: 700,
    state: 1,
  },
  {
    id: 88,
    first_name: 'Adey',
    surname: 'Bellefonte',
    age: 39,
    gender: 'Female',
    level: 600,
    state: 1,
  },
  {
    id: 89,
    first_name: 'Merle',
    surname: 'Doale',
    age: 55,
    gender: 'Male',
    level: 300,
    state: 1,
  },
  {
    id: 90,
    first_name: 'Cindra',
    surname: 'Ordidge',
    age: 32,
    gender: 'Female',
    level: 400,
    state: 1,
  },
  {
    id: 91,
    first_name: 'Valeria',
    surname: 'Eard',
    age: 51,
    gender: 'Female',
    level: 700,
    state: 1,
  },
  {
    id: 92,
    first_name: 'Ahmed',
    surname: 'Yurov',
    age: 54,
    gender: 'Male',
    level: 200,
    state: 1,
  },
  {
    id: 93,
    first_name: 'Shelia',
    surname: 'Bott',
    age: 44,
    gender: 'Female',
    level: 400,
    state: 1,
  },
  {
    id: 94,
    first_name: 'Linzy',
    surname: 'Ransom',
    age: 20,
    gender: 'Female',
    level: 300,
    state: 1,
  },
  {
    id: 95,
    first_name: 'Sindee',
    surname: 'Elies',
    age: 13,
    gender: 'Female',
    level: 500,
    state: 1,
  },
  {
    id: 96,
    first_name: 'Kim',
    surname: 'Rohfsen',
    age: 33,
    gender: 'Male',
    level: 600,
    state: 1,
  },
  {
    id: 97,
    first_name: 'Layton',
    surname: 'Whotton',
    age: 25,
    gender: 'Male',
    level: 700,
    state: 1,
  },
  {
    id: 98,
    first_name: 'Ariel',
    surname: 'Steffan',
    age: 47,
    gender: 'Male',
    level: 600,
    state: 1,
  },
  {
    id: 99,
    first_name: 'Madelina',
    surname: 'Coltart',
    age: 12,
    gender: 'Female',
    level: 500,
    state: 1,
  },
  {
    id: 100,
    first_name: 'Esma',
    surname: 'Lonergan',
    age: 13,
    gender: 'Female',
    level: 300,
    state: 1,
  },
];
